### ISSUE TITLE
Question: "Rarefaction curve"

### ISSUE THREAD

**Issue by weedcentipede** [timjeske/DEUS#1]
Hello,
I'm wondering if I could use this package to generate a "rarefaction" curve for libraries of sRNA-seq,

Cheers,
Luis Alfonso.

**Comment by timjeske** [comment]
Dear Luis Alfonso, 

thank you for your interest in DEUS! 

Currently, DEUS offers no option to create a "rarefaction" curve directly. 
However, after sampling a subset of sequences you could use the [createCountTableFromFastQs()](https://timjeske.github.io/DEUS/reference/createCountTableFromFastQs.html) function to count the number of different sequences or use [runClustering()](https://timjeske.github.io/DEUS/reference/runClustering.html) to compute the number of sequence clusters.

I hope this is helpful for you! Let us know if you have any further questions!

Kind regard
Tim
